# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push: # 将工作流设置为在将事件推送到 main and release/* 分支时运行
    branches: [ "main" ]
#    tags:
#      - v*
  pull_request: # 将工作流设置为在面向 main 分支的事件上运行 pull_request
      branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyfiglet tk pyinstaller

    - name: Compile and pack
      run: |
        pyinstaller -F --noconfirm --windowed --collect-all pyfiglet GetMusicGUI.py
        ls -l dist

    - name: Archive .app files
      uses: actions/upload-artifact@v3.1.3
      with:
        name: GetMusicGUI-${{ runner.os }}
        path: dist/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: v0.9.${{ github.run_number }}
        release_name: Release v0.9.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Download .app files
      uses: actions/download-artifact@v3.0.2
      with:
        name: GetMusicGUI-${{ runner.os }}
        path: artifact

    - name: List files in workspace
      run: |
        ls -l ${{ github.workspace }}
        ls -l dist
        ls -l artifact
        mv artifact/GetMusicGUI artifact/GetMusicGUI-${{ runner.os }}

    - name: Upload .app files to Release
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        ls -l ${{ github.workspace }}
        ls -l artifact
        gh release upload v0.9.${{ github.run_number }} artifact/*

  upload-macos:
      needs: build
      runs-on: macos-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyfiglet tk pyinstaller

      - name: Compile and pack
        run: |
          pyinstaller -F --noconfirm --windowed --collect-all pyfiglet GetMusicGUI.py
          ls -l dist

      - name: Archive .app files
        uses: actions/upload-artifact@v3.1.3
        with:
          name: GetMusicGUI-${{ runner.os }}
          path: dist/*

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: GetMusicGUI-${{ runner.os }}
          path: artifact

      - name: List files in workspace
        run: |
          ls -l ${{ github.workspace }}
          ls -l dist
          ls -l artifact
          mv artifact/GetMusicGUI artifact/GetMusicGUI-${{ runner.os }}
          mv artifact/GetMusicGUI.app artifact/GetMusicGUI-${{ runner.os }}.app
          zip -r artifact/GetMusicGUI-${{ runner.os }}.zip artifact/GetMusicGUI-${{ runner.os }}.app
          rm -rf artifact/GetMusicGUI-${{ runner.os }}.app
          ls -l artifact

      - name: Upload .app files to Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          ls -l ${{ github.workspace }}
          ls -l artifact
          gh release upload v0.9.${{ github.run_number }} artifact/*