# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push: # 将工作流设置为在将事件推送到 main and release/* 分支时运行
    branches: [ "main" ]
#    tags:
#      - v*
  pull_request: # 将工作流设置为在面向 main 分支的事件上运行 pull_request
      branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyfiglet tk pyinstaller

    - name: Compile and pack
      run: |
        pyinstaller -F --noconfirm --windowed --collect-all pyfiglet GetMusicGUI.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: v0.9.${{ github.run_number }} - ${{ runner.os }}
        release_name: Release v0.9.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload .app file to Release
      uses: actions/upload-artifact@v3.1.3
      with:
        name: GetMusicGUI.app
        path: dist/*
